name: iOS Build (Unsign)

on:
  push:
    branches: ["main"]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install JS dependencies
        run: |
          npm install

      - name: Install pods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build .ipa (no signing)
        run: |
          set -e
          xcodebuild \
            -workspace ios/DeployTest.xcworkspace \
            -scheme DeployTest \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/DeployTest.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            clean archive

          xcodebuild \
            -exportArchive \
            -archivePath build/DeployTest.xcarchive \
            -exportPath build \
            -exportOptionsPlist ios/ExportOptions.plist \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DeployTest-ipa
          path: build/DeployTest.ipa
